name: Build

on: [push, pull_request]

jobs:
  archlinux:
    name: Arch Linux
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm --needed \
          clang \
          cmake \
          git \
          mold \
          ninja \
          pkgconf \
          xmake

      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Build
        run: |
          xmake --root -y

  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    container:
      image: ubuntu:noble

    steps:
      - name: Install dependencies
        run: |
          echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
          apt-get update -qq
          apt-get install --no-install-recommends -y \
          7zip \
          ca-certificates \
          cmake \
          git \
          gnupg \
          gcc-14 \
          g++-14 \
          libzstd-dev \
          lsb-release \
          mold \
          ninja-build \
          software-properties-common \
          wget \
          zlib1g-dev

      - name: Install xmake
        run: |
          export XMAKE_ROOT=y
          wget https://xmake.io/shget.text -O - | bash
          update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 200
          update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 200

      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Build
        run: |
          xmake --root -y
